#pragma once
#include "utils/carbon_commons.h"

typedef enum {
	TokenLeftParen,
	TokenRightParen,
	TokenLeftBracket,
	TokenRightBracket,
	TokenLeftBrace,
	TokenRightBrace,
	TokenLeftAInit,
	TokenRightAInit,
	TokenPlus,
	TokenMinus,
	TokenSlash,
	TokenStar,
	TokenPercent,
	TokenPercentEquals,
	TokenPlusEquals,
	TokenMinusEquals,
	TokenSlashEquals,
	TokenStarEquals,
	TokenStringLiteral,
	TokenInteger,
	TokenDecimal,
	TokenBang,
	TokenEquals,
	TokenEqualsEquals,
	TokenBangEquals,
	TokenGEQ,
	TokenLEQ,
	TokenLessThan,
	TokenGreaterThan,
	TokenColon,
	TokenIdentifier,
	TokenFor,
	TokenIn,
	TokenArray,
	TokenGenerator,
	TokenFunction,
	TokenTable,
	TokenError,
	TokenWhile,
	TokenAnd,
	TokenIs,
	TokenAs,
	TokenOr,
	TokenEnd,
	TokenComma,
	TokenDot,
	TokenDotDot,
	TokenBreak,
	TokenContinue,
	TokenReturn,
	TokenInt,
	TokenDouble,
	TokenUInt,
	TokenString,
	TokenObject,
	TokenBool,
	TokenQuestion,
	TokenClass,
	TokenSuper,
	ErrorToken,
	TokenEOF,
	TokenEOS,
	TokenIf,
	TokenElse,
	TokenElif,
	TokenTrue,
	TokenFalse,
	TokenPrint,
	TokenVoid,
	TokenNull,
	TokenClassname,
	TokenImport,
	TokenNone
} CarbonTokenType;

typedef struct {
	char *lexeme;
	char* file;
	CarbonTokenType type;
	uint32_t length;
	uint32_t line;
} CarbonToken;
